
services:

    the-monaco-heist-server:
        
        container_name: the-monaco-heist-server

        image: softwareshinobi/the-monaco-heist:server

        build: 

            context: server

            dockerfile: Dockerfile

        hostname: essenza

        domainname: essenza.embanet.online

        ports:

            - "3547:22"

    the-monaco-heist-web:

        container_name: the-monaco-heist-web

        image: softwareshinobi/the-monaco-heist:web

        build: 

            context: web

            dockerfile: Dockerfile

        ports:

            - "3580:80"
