
services:

    he-monaco-heist-server:
        
        container_name: the-monaco-heist-server

        image: softwareshinobi/the-monaco-heist:server

        build: 

            context: server

            dockerfile: Dockerfile

        hostname: shinobilinux

        domainname: linux.softwareshinobi.com

        ports:

            - "2222:22"

    the-monaco-heist-docs:

        container_name: the-monaco-heist-docs

        image: softwareshinobi/the-monaco-heist:docs

        build: 

            context: landing

            dockerfile: Dockerfile

        ports:

            - 2280:80
